# Generated by Django 3.0.3 on 2020-07-23 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20200723_1941'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogDetail',
            new_name='Blog',
        ),
    ]
