# Generated by Django 3.0.3 on 2020-07-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_auto_20200723_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authordetail',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
